name: 'Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        go-version:
          - 1.20.x
        mruby-version:
          - 3.2.0
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup mruby
        uses: elct9620/setup-mruby@main
        with:
          mruby-version: ${{ matrix.mruby-version }}
      - name: Run Test with CodeClimate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -v -coverprofile coverage.out ./...
          prefix: ${{ github.event.repository.name }}
          coverageLocations:
            "${{github.workspace}}/coverage.out:gocov"

