name: 'Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        go-version:
          - 1.20.x
        mruby-version:
          - 3.2.0
          - 3.3.0
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup mruby
        uses: elct9620/setup-mruby@main
        with:
          mruby-version: ${{ matrix.mruby-version }}
      - name: Run tests
        run: go test -coverprofile=coverage.txt --godog.format=junit ./...
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: platform-${{ matrix.platform }}-mruby-v${{ matrix.mruby-version }}-go-v${{ matrix.go-version }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: go-${{ matrix.go-version }},mruby-${{ matrix.mruby-version }},platform-${{ matrix.platform }}
