name: 'Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        go-version:
          - 1.20.x
        mruby-version:
          - 3.2.0
          - 3.3.0
        platform: [ubuntu-latest, macos-13]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup mruby
        uses: elct9620/setup-mruby@main
        with:
          mruby-version: ${{ matrix.mruby-version }}
      - name: Run Test with CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -v -coverprofile coverage.out ./...
          prefix: github.com/${{ github.event.repository.full_name }}
          coverageLocations:
            "${{github.workspace}}/coverage.out:gocov"

